name: Push & Release
on:
  push:
    branches: [ master, main ]
    tags: [ '*' ]

jobs:
  build-project:
    name: Build Project
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit

  create-release:
    name: Create Release
    needs: build-project
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: '*-windows-x64'
          path: dist
          merge-multiple: true

      - name: Zip Release
        run: |
          cd dist
          NAME="${{ needs.build-project.outputs.pluginName }}"
          VERSION="${{ needs.build-project.outputs.pluginVersion }}"
          
          echo "Zipping for $NAME v$VERSION..."
          zip -r "../${NAME}-${VERSION}-windows-x64.zip" ./*

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.build-project.outputs.pluginName }}-${{ needs.build-project.outputs.pluginVersion }}-windows-x64.zip
          draft: true
          prerelease: false
          generate_release_notes: true